name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout aries-framework-javascript
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          fetch-depth: 0
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set git tag
        run: |
          git tag alpha.1
          git push origin alpha.1 --no-verify
